### ISSUE TITLE
head请求报错，能写个示例吗，想用一下，但是不知道怎么用

### ISSUE THREAD

**Issue by sunyaf** [jianggujin/JHttp#1]

**Comment by jianggujin** [comment]
@sunyaf 报的应该是java.io.EOFException的错误，是因为服务器响应头中：Content-Encoding为gzip，如果使用默认的响应对象处理，会对其进行包裹，使用java.util.zip.GZIPInputStream导致的错误，针对head请求是没有响应体的，可以自定义一个响应对象处理，可以参考：
package com.jianggujin.http.response;

import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.util.List;
import java.util.Map;

import com.jianggujin.http.core.JRequest;
import com.jianggujin.http.core.JResponse;

/**
 * 无响应体实现
 * 
 * @author jianggujin
 *
 */
public class JNoBodyResponse implements JResponse {
   protected int responseCode;
   protected String responseMessage;
   protected Map<String, List<String>> headers;
   protected boolean isError;

   public void onComplete(InputStream inputStream, HttpURLConnection conn, JRequest request) throws IOException {
      this.responseCode = conn.getResponseCode();
      this.responseMessage = conn.getResponseMessage();
      this.headers = conn.getHeaderFields();
      this.responseCode = conn.getResponseCode();
      this.isError = responseCode != 200; // responseCode < 200 || responseCode
      if (this.isError && !request.ignoreError())
         throw new IOException("the http response status[" + responseCode + "] is not 200.");
   }

   /**
    * 获得响应吗
    * 
    * @return responseCode
    */
   public int getResponseCode() {
      return responseCode;
   }

   /**
    * 获得响应消息
    * 
    * @return responseMessage
    */
   public String getResponseMessage() {
      return responseMessage;
   }

   /**
    * 获得响应头
    * 
    * @return headers
    */
   public Map<String, List<String>> getHeaders() {
      return headers;
   }

   /**
    * 获得响应头
    */
   public String getHeader(String name) {
      List<String> headers = this.headers.get(name);
      if (headers != null && !headers.isEmpty())
         return headers.get(0);
      return null;
   }

   /**
    * 是否错误
    * 
    * @return isError
    */
   public boolean isError() {
      return isError;
   }

   /**
    * 获得数据
    * 
    * @return data
    */
   public Object getData() {
      return null;
   }

   public Object getError() {
      return null;
   }

}

**Comment by jianggujin** [comment]
v1.0.1已添加默认的无响应体处理，轻尝试使用最新版
