### ISSUE TITLE
请求时间过长

### ISSUE THREAD

**Issue by sunyaf** [jianggujin/JHttp#2]
我创建了一个请求，
`               
                long l = System.currentTimeMillis();
                execute = JRequest.create("https://book.douban.com/subject/30163860/").method(JMethod.HEAD).execute();
                JResponse response = execute.response();
                System.out.println(response.getResponseCode());
                System.out.println("存在:时间"+(System.currentTimeMillis()-l));`
这个输出的时间是9088多毫秒，但是请求同样的地址，我再postman里面测试的是500ms,请问一下，这是什么原因啊

**Comment by jianggujin** [comment]
单纯的一次测试没有意义，可以尝试请求多次取平均值，参考代码：
package com.jianggujin.http.test;

import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;

import org.apache.http.client.HttpClient;
import org.apache.http.client.config.RequestConfig;
import org.apache.http.client.methods.HttpHead;
import org.apache.http.impl.client.HttpClientBuilder;
import org.junit.Test;

import com.jianggujin.http.core.JMethod;
import com.jianggujin.http.core.JRequest;

public class PressureTest {
   String url = "https://book.douban.com/subject/30163860/";
   int count = 50;

   @Test
   public void useJHttp() throws IOException {
      long start = System.currentTimeMillis();
      for (int i = 0; i < count; i++) {
         JRequest.create(url).method(JMethod.HEAD).execute();
      }
      long sum = System.currentTimeMillis() - start;
      System.out.println("JHttp总时间：" + sum + "ms");
      System.out.println("JHttp平均时间：" + (sum / count) + "ms");
   }

   @Test
   public void useHttpUrlConnection() throws IOException {
      long start = System.currentTimeMillis();
      for (int i = 0; i < count; i++) {
         HttpURLConnection conn = (HttpURLConnection) new URL(url).openConnection();
         conn.setRequestMethod("HEAD");
         conn.setConnectTimeout(5000);
         conn.setReadTimeout(5000);
         conn.connect();
         conn.getResponseCode();
      }
      long sum = System.currentTimeMillis() - start;
      System.out.println("HttpUrlConnection总时间：" + sum + "ms");
      System.out.println("HttpUrlConnection平均时间：" + (sum / count) + "ms");
   }

   @Test
   public void useHttpClient() throws IOException {
      long start = System.currentTimeMillis();
      RequestConfig requestConfig = RequestConfig.custom().setConnectTimeout(5000).setSocketTimeout(5000)
            .setConnectionRequestTimeout(5000).build();
      HttpClient client = HttpClientBuilder.create().setDefaultRequestConfig(requestConfig).build();
      for (int i = 0; i < count; i++) {
         HttpHead head = new HttpHead(url);
         client.execute(head).getStatusLine();
      }
      long sum = System.currentTimeMillis() - start;
      System.out.println("HttpClient总时间：" + sum + "ms");
      System.out.println("HttpClient平均时间：" + (sum / count) + "ms");
   }

}


HttpClient坐标：
<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpclient</artifactId>
    <version>4.5.6</version>
    <scope>test</scope>
</dependency>

**Comment by sunyaf** [comment]
加一下qq好吧，我有些问题关于你这个项目的，想和你探讨一下哈
475387797，我的名字孙亚飞
